apiVersion: v1
kind: ConfigMap
metadata:
  name: php-app-config
data:
  DB_HOST: {{ .Values.db.host }}
  DB_USER: {{ .Values.db.user }}
  DB_PASS: {{ .Values.db.pass }}
  DB_NAME: {{ .Values.db.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.php.name }}
spec:
  replicas: {{ .Values.php.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.php.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.php.name }}
    spec:
      containers:
      - name: {{ .Values.php.name }}
        image: {{ .Values.php.image }}
        envFrom:
        - configMapRef:
            name: php-app-config
        ports:
        - containerPort: {{ .Values.php.port }}
          name: http
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceOneName }}
  labels:
    app: {{ .Values.php.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.php.name }}
  ports:
  - name: http
    port: {{ .Values.php.port }}
    targetPort: {{ .Values.php.port }}
    nodePort: 30080




# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: php-app-config
# data:
#   DB_HOST: mysql-service
#   DB_USER: tms_user
#   DB_PASS: tms_password
#   DB_NAME: tms


# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: php
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: php
#   template:
#     metadata:
#       labels:
#         app: php
#     spec:
#       containers:
#       - name: php
#         image: mksvk/php:7.0
#         envFrom:
#         - configMapRef:
#             name: php-app-config
#         ports:
#         - containerPort: 80
#           name: http